development:
  adapter: async

test:
  adapter: async

production:
  :url: redis://redistogo:aa8fd57b56bd0649fbfbcdda9515f4fe@pike.redistogo.com:10920/
  :host: dory.redistogo.com
  :port: 11403
  :inline: true
  :timeout: 1
